services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network

  app:
    build: .
    command: gunicorn Group_chat.wsgi:application --bind 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./db.sqlite3
        target: /root/db.sqlite3
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.2.5
    networks:
      - app-network

networks:
  app-network:
