services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/root/home/static
    depends_on:
      - app
    networks:
      - app-network

  app:
    build: .
    command: gunicorn Group_chat.wsgi:application --bind 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - static:/root/home/static
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.2.5
    networks:
      - app-network

networks:
  app-network:

volumes:
  static: